# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductList', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='createdon',
        ),
    ]
