# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 03:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductList', '0003_remove_comment_createdon'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='createdon',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
