# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductList', '0004_comment_createdon'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.TextField(choices=[('Kitchen', 'Kitchen'), ('Entertainment', 'Entertainment'), ('Bedroom', 'Bedroom'), ('None', 'None')], default='None'),
        ),
    ]
