# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductList', '0006_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.TextField(choices=[('Kitchen', 'Kitchen'), ('Entertainment', 'Entertainment'), ('Bedroom', 'Bedroom'), ('None', 'None')], default='None')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='bundles',
            field=models.ManyToManyField(to='ProductList.Bundle'),
        ),
    ]
