# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductList', '0006_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('devices', models.TextField(choices=[('Amazon Echo', 'Amazon Echo'), ('Google Home', 'Google Home'), ('Ring Video Doorbell', 'Ring Video Doorbell'), ('Logitech Harmony Home Hub', 'Logitech Harmony Home Hub'), ('Nest Thermostat', 'Nest Thermostat'), ('Ecobee Remote Sensor', 'Ecobee Remote Sensor'), ('Philips Hue', 'Philips Hue'), ('Bose sound link Bluetooth Speaker', 'Bose sound link Bluetooth Speaker')], default='None')),
            ],
        ),
    ]
