# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductList', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default='None', max_length=200),
        ),
    ]
