# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ProductList', '0010_auto_20170422_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
