# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductList', '0012_bundle__price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='_price',
        ),
    ]
