# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-23 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductList', '0013_remove_bundle__price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
