# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductList', '0017_auto_20170424_1938'),
        ('ProductList', '0008_user_username'),
    ]

    operations = [
    ]
