# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductList', '0019_auto_20170425_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='devices',
            field=models.TextField(default='None'),
        ),
    ]
