# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductList', '0020_auto_20170425_1316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
