# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductList', '0023_auto_20170501_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isOwned',
            field=models.BooleanField(default=False),
        ),
    ]
