# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductList', '0024_item_isowned'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='asin',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
